-- CreateEnum
CREATE TYPE "UnitType" AS ENUM ('residential', 'commercial');

-- CreateTable
CREATE TABLE "Unit" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "propertyId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "marketRateCents" INTEGER NOT NULL,
    "unitType" "UnitType" NOT NULL DEFAULT 'residential',
    "bedrooms" INTEGER,
    "bathrooms" DECIMAL(4,1),
    "squareFeet" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Unit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UtilityType" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "label" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UtilityType_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AmenityOption" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "label" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AmenityOption_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UnitUtility" (
    "unitId" INTEGER NOT NULL,
    "optionId" INTEGER NOT NULL,

    CONSTRAINT "UnitUtility_pkey" PRIMARY KEY ("unitId","optionId")
);

-- CreateTable
CREATE TABLE "UnitAmenity" (
    "unitId" INTEGER NOT NULL,
    "optionId" INTEGER NOT NULL,

    CONSTRAINT "UnitAmenity_pkey" PRIMARY KEY ("unitId","optionId")
);

-- CreateIndex
CREATE UNIQUE INDEX "Unit_propertyId_name_key" ON "Unit"("propertyId", "name");

-- CreateIndex
CREATE INDEX "Unit_propertyId_idx" ON "Unit"("propertyId");

-- CreateIndex
CREATE UNIQUE INDEX "UtilityType_label_key" ON "UtilityType"("label");

-- CreateIndex
CREATE UNIQUE INDEX "AmenityOption_label_key" ON "AmenityOption"("label");

-- CreateIndex
CREATE INDEX "UnitUtility_optionId_idx" ON "UnitUtility"("optionId");

-- CreateIndex
CREATE INDEX "UnitAmenity_optionId_idx" ON "UnitAmenity"("optionId");

-- AddForeignKey
ALTER TABLE "Unit" ADD CONSTRAINT "Unit_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnitUtility" ADD CONSTRAINT "UnitUtility_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnitUtility" ADD CONSTRAINT "UnitUtility_optionId_fkey" FOREIGN KEY ("optionId") REFERENCES "UtilityType"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnitAmenity" ADD CONSTRAINT "UnitAmenity_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnitAmenity" ADD CONSTRAINT "UnitAmenity_optionId_fkey" FOREIGN KEY ("optionId") REFERENCES "AmenityOption"("id") ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO "UtilityType" ("label", "sortOrder", "updatedAt") VALUES
  ('Electricity', 10, CURRENT_TIMESTAMP),
  ('Water', 20, CURRENT_TIMESTAMP),
  ('Sewer', 30, CURRENT_TIMESTAMP),
  ('Gas', 40, CURRENT_TIMESTAMP),
  ('Internet', 50, CURRENT_TIMESTAMP);

INSERT INTO "AmenityOption" ("label", "sortOrder", "updatedAt") VALUES
  ('A/C', 10, CURRENT_TIMESTAMP),
  ('Off-Street Parking', 20, CURRENT_TIMESTAMP),
  ('On-Street Parking', 30, CURRENT_TIMESTAMP),
  ('Pool', 40, CURRENT_TIMESTAMP),
  ('Furnished', 50, CURRENT_TIMESTAMP),
  ('Balcony/Deck', 60, CURRENT_TIMESTAMP),
  ('Hardwood Floor', 70, CURRENT_TIMESTAMP),
  ('Tile Floor', 80, CURRENT_TIMESTAMP),
  ('Carpet', 90, CURRENT_TIMESTAMP),
  ('Pets Allowed', 100, CURRENT_TIMESTAMP),
  ('Wheelchair Access', 110, CURRENT_TIMESTAMP);
