ALTER TABLE "Lease" ALTER COLUMN "propertyId" DROP NOT NULL;

ALTER TABLE "Lease" ALTER COLUMN "unitId" DROP NOT NULL;

ALTER TABLE "Lease" ALTER COLUMN "monthlyRentCents" DROP NOT NULL;

ALTER TABLE "Lease" ALTER COLUMN "startsOn" DROP NOT NULL;
