import { jobDashboardFavIcon, jobDashboardLightLogoUrl } from "./job-dashboard-branding";

export const jobDashboardOptions = {
  uiConfig: {
    boardTitle: "Parcelis Jobs",
    boardLogo: { path: jobDashboardLightLogoUrl, width: 36, height: 36 },
    favIcon: jobDashboardFavIcon,
    hideDocsLink: true,
    hideRedisDetails: true,
    theme: {
      light: {
        background: "#f7f8f6",
        foreground: "#101c29",
        card: "#ffffff",
        "card-foreground": "#101c29",
        popover: "#ffffff",
        "popover-foreground": "#101c29",
        primary: "#6fa640",
        "primary-foreground": "#101c29",
        secondary: "#e9eee7",
        "secondary-foreground": "#101c29",
        muted: "#eef0ed",
        "muted-foreground": "#586273",
        accent: "#eaf1e5",
        "accent-foreground": "#101c29",
        border: "#dce1dc",
        input: "#dce1dc",
        ring: "#6fa640",
        radius: "0.5rem",
        sidebar: "#101c29",
        "sidebar-foreground": "#f7f8f6",
        "sidebar-primary": "#6fa640",
        "sidebar-primary-foreground": "#101c29",
        "sidebar-accent": "#172635",
        "sidebar-accent-foreground": "#f7f8f6",
        "sidebar-border": "#35464a",
        "sidebar-ring": "#6fa640",
      },
      dark: {
        background: "#101c29",
        foreground: "#f7f8f6",
        card: "#172635",
        "card-foreground": "#f7f8f6",
        popover: "#172635",
        "popover-foreground": "#f7f8f6",
        primary: "#89b960",
        "primary-foreground": "#101c29",
        secondary: "#233647",
        "secondary-foreground": "#f7f8f6",
        muted: "#233647",
        "muted-foreground": "#b3bec8",
        accent: "#263d50",
        "accent-foreground": "#f7f8f6",
        border: "#35464a",
        input: "#35464a",
        ring: "#89b960",
        radius: "0.5rem",
        sidebar: "#101c29",
        "sidebar-foreground": "#f7f8f6",
        "sidebar-primary": "#89b960",
        "sidebar-primary-foreground": "#101c29",
        "sidebar-accent": "#172635",
        "sidebar-accent-foreground": "#f7f8f6",
        "sidebar-border": "#35464a",
        "sidebar-ring": "#89b960",
      },
    },
  },
};
