-- CreateEnum
CREATE TYPE "MaintenanceRequesterType" AS ENUM ('tenant', 'landlord');

-- CreateTable
CREATE TABLE "Landlord" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Landlord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MaintenanceCategory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "label" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "MaintenanceCategory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MaintenanceTicketUnit" (
    "ticketId" INTEGER NOT NULL,
    "unitId" INTEGER NOT NULL,
    CONSTRAINT "MaintenanceTicketUnit_pkey" PRIMARY KEY ("ticketId", "unitId")
);

-- AlterTable
ALTER TABLE "MaintenanceTicket" ADD COLUMN "categoryId" INTEGER,
ADD COLUMN "isUrgent" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "requestedByLandlordId" INTEGER,
ADD COLUMN "requestedByTenantId" INTEGER,
ADD COLUMN "requestedByType" "MaintenanceRequesterType";

-- CreateIndex
CREATE UNIQUE INDEX "Landlord_email_key" ON "Landlord"("email");
CREATE UNIQUE INDEX "MaintenanceCategory_label_key" ON "MaintenanceCategory"("label");
CREATE INDEX "MaintenanceTicket_categoryId_idx" ON "MaintenanceTicket"("categoryId");
CREATE INDEX "MaintenanceTicket_requestedByTenantId_idx" ON "MaintenanceTicket"("requestedByTenantId");
CREATE INDEX "MaintenanceTicket_requestedByLandlordId_idx" ON "MaintenanceTicket"("requestedByLandlordId");
CREATE INDEX "MaintenanceTicketUnit_unitId_idx" ON "MaintenanceTicketUnit"("unitId");

-- AddForeignKey
ALTER TABLE "MaintenanceTicket" ADD CONSTRAINT "MaintenanceTicket_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "MaintenanceCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceTicket" ADD CONSTRAINT "MaintenanceTicket_requestedByTenantId_fkey" FOREIGN KEY ("requestedByTenantId") REFERENCES "Tenant"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceTicket" ADD CONSTRAINT "MaintenanceTicket_requestedByLandlordId_fkey" FOREIGN KEY ("requestedByLandlordId") REFERENCES "Landlord"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceTicketUnit" ADD CONSTRAINT "MaintenanceTicketUnit_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "MaintenanceTicket"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MaintenanceTicketUnit" ADD CONSTRAINT "MaintenanceTicketUnit_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE CASCADE ON UPDATE CASCADE;
