name: Post GitHub notifications to Discord

on:
  pull_request:
    types: [opened, reopened, closed]
  issues:
    types: [opened, closed]

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_PR_WEBHOOK_URL: ${{ secrets.DISCORD_PR_WEBHOOK_URL }}
    steps:
      - name: Send new PR notification
        if: github.event_name == 'pull_request' && github.event.action != 'closed' && env.DISCORD_PR_WEBHOOK_URL != ''
        uses: stegzilla/discord-notify@23eb4dd9a5eab4ab63c65cbe554bdf837f9fe773 # v5
        with:
          webhook_url: ${{ env.DISCORD_PR_WEBHOOK_URL }}
          title: "Pull request opened: ${{ github.event.pull_request.title }}"
          message: |
            Creator: ${{ github.event.pull_request.user.login }}
            ${{ github.event.pull_request.html_url }}

      - name: Send new issue notification
        if: github.event_name == 'issues' && github.event.action == 'opened' && env.DISCORD_PR_WEBHOOK_URL != ''
        uses: stegzilla/discord-notify@23eb4dd9a5eab4ab63c65cbe554bdf837f9fe773 # v5
        with:
          webhook_url: ${{ env.DISCORD_PR_WEBHOOK_URL }}
          title: "Issue opened: ${{ github.event.issue.title }}"
          message: |
            Creator: ${{ github.event.issue.user.login }}
            ${{ github.event.issue.html_url }}

      - name: Send closed PR notification
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && env.DISCORD_PR_WEBHOOK_URL != ''
        uses: stegzilla/discord-notify@23eb4dd9a5eab4ab63c65cbe554bdf837f9fe773 # v5
        with:
          webhook_url: ${{ env.DISCORD_PR_WEBHOOK_URL }}
          title: Pull request closed — ${{ github.event.pull_request.title }}
          message: |
            Creator: ${{ github.event.pull_request.user.login }}
            ${{ github.event.pull_request.html_url }}

      - name: Send closed issue notification
        if: github.event_name == 'issues' && github.event.action == 'closed' && env.DISCORD_PR_WEBHOOK_URL != ''
        uses: stegzilla/discord-notify@23eb4dd9a5eab4ab63c65cbe554bdf837f9fe773 # v5
        with:
          webhook_url: ${{ env.DISCORD_PR_WEBHOOK_URL }}
          title: Issue closed — ${{ github.event.issue.title }}
          message: |
            Creator: ${{ github.event.issue.user.login }}
            ${{ github.event.issue.html_url }}
