name: Linter

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review, converted_to_draft]

jobs:
  lint:
    name: Run Lint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history so commitlint can inspect previous commits

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.34.5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.19.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Commit Lint
        run: pnpm lint:commits --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}

      - name: Run Turbo Linter
        run: pnpm lint
